services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_USER=${SQL_USER}
    ports:
      - '5433:5432'

  minio:
    restart: always
    image: minio/minio:latest
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS}
      MINIO_SECRET_KEY: ${MINIO_SECRET}
    command: server /data --console-address :9090
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    restart: always
    volumes:
        - redis_data:/data

volumes:
  minio-data:
  redis_data: