services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=cloudfilestoragedb
      - POSTGRES_PASSWORD=14159265
      - POSTGRES_USER=postgres
    ports:
      - '5433:5432'

  minio:
    restart: always
    image: minio/minio:latest
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address :9090
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    restart: always
    volumes:
        - redis_data:/data

volumes:
  minio-data:
  redis_data: